### Récupération d'une liste random de livre
GET http://localhost:3001/api/books/random

###Récupérer tout les livres
GET http://localhost:3001/api/books


###Récupérer un seul livre par son id
GET http://localhost:3001/api/books/2



# Test pour Register, Login et Logout

### Tester l'inscription d'un utilisateur
POST http://localhost:3001/api/users/register
Content-Type: application/json

{
    "username": "Benons",
    "firstname": "Delly",
    "lastname": "Delabarre",
    "email": "actest@example.com",
    "password": "Test@1234",
    "biography": "Développeur passionné"
}

### Tester l'inscription d'un utilisateur
POST http://localhost:3001/api/users/register
Content-Type: application/json

{
    "username": "Noelito",
    "firstname": "isradis",
    "lastname": "laarif",
    "email": "aNoel@example.com",
    "password": "Test@1234"
    
}

### Tester la connexion d'un utilisateur
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "email": "aNoel@example.com",
    "password": "Test@1234"
}


### Récupérer les informations de l'utilisateur connecté
GET http://localhost:3001/api/users/connected-user
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJvbGZhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzM5ODIwMzU2LCJleHAiOjE3Mzk5MDY3NTZ9.PKUWNS7ocxRB9vxn_j2iTGtwJ3R4eF-1v4ySEYdQeHA


### Tester la déconnexion d'un utilisateur
GET http://localhost:3001/api/users/logout