### Récupération d'une liste random de livre
GET http://localhost:3001/api/books/random

###Récupérer tout les livres
GET http://localhost:3001/api/books


###Récupérer un seul livre par son id
GET http://localhost:3001/api/books/2



# Test pour Register, Login et Logout

### Tester l'inscription d'un utilisateur
POST http://localhost:3001/api/users/register
Content-Type: application/json

{
    "username": "Benons",
    "firstname": "Delly",
    "lastname": "Delabarre",
    "email": "actest@example.com",
    "password": "Test@1234",
    "biography": "Développeur passionné"
}

### Tester l'inscription d'un utilisateur
POST http://localhost:3001/api/users/register
Content-Type: application/json

{
    "username": "olfa-test",
    "firstname": "olfa",
    "lastname": "laarif",
    "email": "testolfa@example.com",
    "password": "Test@1234"
    
}

### Tester la connexion d'un utilisateur
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "email": "testolfa@example.com",
    "password": "Test@1234"
}

### Tester la déconnexion d'un utilisateur
GET http://localhost:3001/api/users/logout


### Récupérer les informations de l'utilisateur connecté
GET http://localhost:3001/api/users/connected-user
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoidGVzdG9sZmFAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mzk5MTU4ODIsImV4cCI6MTc0MDAwMjI4Mn0.HlqKVUPcaZ3uWYgVQQML3SQ2gbmGpBcpTENiqkxDRdg
###Récupérer un utilisateur par son email
GET http://localhost:3001/api/user/email/testolfa@example.com

###Récupérer un utilisateur par son pseudo
GET http://localhost:3001/api/user/username/olfa-la

###Récupérer un seul utilisateur par son id
GET http://localhost:3001/api/user/13