import { DataTypes, Model } from "sequelize";
import { sequelize } from "./sequelizeClient.js";

export class Category extends Model{};



Category.init({
    name: {
    type: DataTypes.TEXT,
    allowNull: false
    },
}, {
    sequelize,
    tableName: 'category'
});


/*CREATE TABLE "category" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL
);*/
