import { DataTypes, Model } from "sequelize";
import { sequelize } from "./sequelizeClient.js";

export class Mark extends Model{};


Mark.init({
  rating: {
    type: DataTypes.INTEGER,
    allowNull: false
  },
  review: {
    type: DataTypes.TEXT,
    allowNull: false,
  }
}, {
  sequelize,
  tableName: 'mark'
});


/*CREATE TABLE "mark" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "bookId" TEXT NOT NULL REFERENCES "book"("id") ON DELETE CASCADE,
  "rating" INTEGER NOT NULL,
  "review" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ NOT NULL
);*/
