import { DataTypes, Model } from "sequelize";
import { sequelize } from "./sequelizeClient.js";

export class Mark extends Model{};


Mark.init({
  rating: {
    type: DataTypes.INTEGER,
    allowNull: false,
    validate: {
      min: 1,
      max: 5
    }
  },
  review: {
    type: DataTypes.TEXT
  }
}, {
  sequelize,
  tableName: 'mark',
  indexes: [
    {
      unique: true,
      fields: ['UserId', 'BookId'] // Empêche plusieurs avis du même utilisateur pour un livre
    }
  ]
});


/*CREATE TABLE "mark" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "BookId" TEXT NOT NULL REFERENCES "book"("id") ON DELETE CASCADE,
  "rating" INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  "review" TEXT,
  UNIQUE ("UserId", "BookId"),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ NOT NULL
);*/
