import { DataTypes, Model } from "sequelize";
import { sequelize } from "./sequelizeClient.js";

export class User extends Model{};


User.init({
    username : {
      type: DataTypes.TEXT,
      allowNull: false,
      unique: true
    },
    firstname : {
        type: DataTypes.TEXT,
        allowNull: false,
      },
    lastname: {
        type: DataTypes.TEXT,
        allowNull: false,
    },
    email : {
        type: DataTypes.TEXT,
        allowNull: false,
        unique: true
      },
      password : {
        type: DataTypes.TEXT,
        allowNull: false,
      },
      biography : {
        type: DataTypes.TEXT,
      },
  }, {
    sequelize,
    tableName: 'user'
  });



// CREATE TABLE "user" (
//     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     "username" TEXT NOT NULL UNIQUE,
//     "firstname" TEXT NOT NULL,
//     "lastname" TEXT NOT NULL,
//     "email" TEXT NOT NULL UNIQUE,
//     "password" TEXT NOT NULL,
//     "biography" TEXT,
//     "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
//     "updated_at" TIMESTAMPTZ NOT NULL
// );
